### PR TITLE
Fixed platform/board-select filter callback to skip groups.

### LINKED ISSUE #26: Entering a board name results in blank PIO Home screen - 3.x beta
I don't know if this just came in the recent dev builds, but when I try to create a new project via PIO home, trying to enter a board name results in the PIO home screen blanking. If I scroll and pick a name instead of typing it, it works fine... i.e. in this screen recording it blanked when I typed in 'u' for uno... 😮 

pio_home_board_name_blanking_bug

I also caught this output in the developer console when the PIO home tab blanked.

image

Windows 10, VSCode 1.39.2, PIO dev branch (4.1.0rc1), core package versions

```
Checking tool-unity                      @ 1.20403.0      [Up-to-date]
Checking tool-pioplus                    @ 2.5.8          [Up-to-date]
Checking contrib-pysite                  @ 2.27.191017    [Up-to-date]
Checking contrib-piohome                 @ 3.0.0-beta.1   [Up-to-date]
Checking tool-scons                      @ 2.20501.190826 [Up-to-date]
Checking tool-cppcheck                   @ 1.189.0        [Up-to-date]
```

### PR DESCRIPTION
**Pull request by elyulka**
// Resolve #26

### CODE REVIEW

File: app/modules/platform/containers/board-select.jsx [hunk 1]
```diff
@@ -65,9 +65,16 @@ class BoardSelect extends React.Component {
         size="large"
         placeholder={`Select a board (${this.props.items.length} available)`}
         optionFilterProp="children"
-        filterOption={(input, option) =>
-          option.props.children.toLowerCase().includes(input.toLocaleLowerCase())
-        }
+        filterOption={(input, option) => {
+          const { children } = option.props;
+          if (typeof children === 'string') {
```
Comment (ivankravets) [inline app/modules/platform/containers/board-select.jsx]: Please use `option.props.children` without unpacking
